language: go
sudo: false

matrix:
  include:
    - go: 1.2
    - go: 1.3
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
